package me.avankziar.cas.spigot.gui.objects;

public enum GuiType
{
	ADMINISTRATION,
	NUMPAD_ACCOUNT,
	NUMPAD_ITEMINPUT,
	NUMPAD_ITEMSHIFTINPUT,
	NUMPAD_ITEMOUTPUT,
	NUMPAD_ITEMSHIFTOUTPUT,
	KEYBOARD_WHITELIST,
	KEYBOARD_MEMBER,
	KEYBOARD_SIGNSTORAGENAME,
	ITEM_INPUT,
	/*SEARCH_BUY,
	SEARCH_SELL,
	SUBSCIBED*/
}
